### ISSUE TITLE
Filter tests into categories in pipeline

### ISSUE THREAD

**Issue by Marvin-Brouwer** [Marvin-Brouwer/FluentSerializer#16]
We'd like to split up the tests in to separate steps so code coverage can be measured for unit-tests only.
Something like this:
```yml
- name: Unit Test
      run: dotnet test --nologo --no-build --configuration "Release" --filter "Category=UnitTest" --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"
    - name: Use-case Test 
      run: dotnet test --nologo --no-build --configuration "Release" --filter "Category=UseCase"
```
However, when this was tried it resulted in no tests run.

Dependent on: #14
